version: '3.3'
services:
  function:
    container_name: function
    hostname: function
    image: function
    ports:
      - 8111:8111
    entrypoint: [ "java", "-jar", "demo-0.0.1-SNAPSHOT.jar" ]
    expose:
      - 8111
    restart: always